-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 21:11:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdentrepalos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdentrepalos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdentrepalos` DEFAULT CHARACTER SET utf8 ;
USE `bdentrepalos` ;

-- -----------------------------------------------------
-- Table `bdentrepalos`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Mesa` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numero` TINYINT UNSIGNED NOT NULL,
  `Ubicacion` VARCHAR(30) NOT NULL,
  `Capacidad` TINYINT NOT NULL,
  `Ocupacion` ENUM('disponible', 'ocupada') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTblMesa_UNIQUE` (`id` ASC),
  UNIQUE INDEX `TblMesaNumero_UNIQUE` (`Numero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Depatamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Depatamento` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(90) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Municipio` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(90) NOT NULL,
  `Depatamento_id` BIGINT UNSIGNED NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Municipio_Depatamentos1_idx` (`Depatamento_id` ASC),
  CONSTRAINT `fk_Municipio_Depatamentos1`
    FOREIGN KEY (`Depatamento_id`)
    REFERENCES `bdentrepalos`.`Depatamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Empresa` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(40) NOT NULL,
  `NIT` VARCHAR(20) NULL DEFAULT '00000-00',
  `Telefono` BIGINT UNSIGNED NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Municipio_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC),
  INDEX `fk_Empresa_Municipio1_idx` (`Municipio_id` ASC),
  CONSTRAINT `fk_Empresa_Municipio1`
    FOREIGN KEY (`Municipio_id`)
    REFERENCES `bdentrepalos`.`Municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Usuario` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cedula` BIGINT UNSIGNED NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Telefono` BIGINT UNSIGNED NOT NULL,
  `Direccion` VARCHAR(60) NULL,
  `Email` VARCHAR(60) NULL,
  `Contraseña` VARCHAR(20) NULL,
  `Rol` ENUM('Administrador', 'Proveedor', 'Cliente', 'Mesero', 'Cocinero', 'Domiciliario') NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Empresa_id` SMALLINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTblAdministrador_UNIQUE` (`id` ASC),
  UNIQUE INDEX `TblAdministradorCedula_UNIQUE` (`Cedula` ASC),
  UNIQUE INDEX `TblAdministradorTelefono_UNIQUE` (`Telefono` ASC),
  UNIQUE INDEX `TblAdministradorContraseña_UNIQUE` (`Contraseña` ASC),
  UNIQUE INDEX `TblAdministradorEmail_UNIQUE` (`Email` ASC),
  INDEX `fk_Usuario_Empresa1_idx` (`Empresa_id` ASC),
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `bdentrepalos`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Pago` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Trabajador_id` TINYINT UNSIGNED NOT NULL,
  `Fecha` DATE NOT NULL,
  `Estado` ENUM('Pendiente', 'Saldado') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTblPago_UNIQUE` (`id` ASC),
  INDEX `fk_Pago_Usuario1_idx` (`Trabajador_id` ASC),
  CONSTRAINT `fk_Pago_Usuario1`
    FOREIGN KEY (`Trabajador_id`)
    REFERENCES `bdentrepalos`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Factura` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Numero` SMALLINT UNSIGNED NOT NULL,
  `Fecha` DATE NOT NULL,
  `IVA` DECIMAL NULL DEFAULT 0.19,
  `MedioPago` ENUM('Datafono', 'Efectivo', 'Nequi', 'Ahorro a la mano', 'Daviplata') NOT NULL,
  `Mesero_id` TINYINT UNSIGNED NOT NULL,
  `Estado` ENUM('Pendiente', 'Paga', 'Cancelada') NOT NULL,
  `TipoPedido` ENUM('Mesa', 'Domicilio') NOT NULL,
  UNIQUE INDEX `idTblFactura_UNIQUE` (`id` ASC),
  INDEX `fk_Factura_Usuario1_idx` (`Mesero_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Numero_UNIQUE` (`Numero` ASC),
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`Mesero_id`)
    REFERENCES `bdentrepalos`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Subcategoria` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(40) NOT NULL,
  `CategoriaProducto` ENUM('Comida', 'Bebida', 'Postre') NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTblCategoriaProducto_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Marca` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Proveedor_id` TINYINT UNSIGNED NOT NULL,
  `Estado` ENUM('Activa', 'Inactiva') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Marca_Usuario1_idx` (`Proveedor_id` ASC),
  CONSTRAINT `fk_Marca_Usuario1`
    FOREIGN KEY (`Proveedor_id`)
    REFERENCES `bdentrepalos`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Producto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(80) NOT NULL,
  `Tamaño` SMALLINT UNSIGNED NOT NULL,
  `ReferenciaTamaño` ENUM('ml', 'Lt', 'Kg', 'gr', 'Oz', 'Lb') NOT NULL,
  `Referencia` VARCHAR(25) NOT NULL,
  `PrecioBase` MEDIUMINT UNSIGNED NOT NULL,
  `PrecioUnidadTrabajador` MEDIUMINT UNSIGNED NOT NULL,
  `PrecioUnidadVenta` MEDIUMINT UNSIGNED NOT NULL,
  `PresentacionProducto` ENUM('Lata', 'Botella vidrio', 'Botella plastico', 'Tetrapack', 'Predeterminado', 'Icopor', 'Vaso vidrio', 'Vaso plastico', 'Tasa') NOT NULL,
  `Marca_id` INT UNSIGNED NULL,
  `CantidadProducto` SMALLINT UNSIGNED NOT NULL,
  `Subcategoria_id` TINYINT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTblProducto_UNIQUE` (`id` ASC),
  UNIQUE INDEX `TblProductoReferencia_UNIQUE` (`Referencia` ASC),
  INDEX `fk_Producto_Subcategoria1_idx` (`Subcategoria_id` ASC),
  INDEX `fk_Producto_Marca1_idx` (`Marca_id` ASC),
  CONSTRAINT `fk_Producto_Subcategoria1`
    FOREIGN KEY (`Subcategoria_id`)
    REFERENCES `bdentrepalos`.`Subcategoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `bdentrepalos`.`Marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Oferta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `PrecioUnidadVentaOferta` MEDIUMINT NOT NULL,
  `Estado` ENUM('Disponible', 'No disponible') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`DetallePedido` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `Factura_id` INT UNSIGNED NOT NULL,
  `Producto_id` INT UNSIGNED NULL,
  `Ofertas_id` INT NULL,
  `CantidadProducto` SMALLINT NULL,
  `CantidadOferta` SMALLINT NULL,
  `Mesa_id` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_DetallePedido_Producto1_idx` (`Producto_id` ASC),
  INDEX `fk_DetallePedido_Mesa1_idx` (`Mesa_id` ASC),
  INDEX `fk_DetallePedido_Ofertas1_idx` (`Ofertas_id` ASC),
  INDEX `fk_DetallePedido_Factura1_idx` (`Factura_id` ASC),
  CONSTRAINT `fk_DetallePedido_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `bdentrepalos`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Mesa1`
    FOREIGN KEY (`Mesa_id`)
    REFERENCES `bdentrepalos`.`Mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Ofertas1`
    FOREIGN KEY (`Ofertas_id`)
    REFERENCES `bdentrepalos`.`Oferta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Factura1`
    FOREIGN KEY (`Factura_id`)
    REFERENCES `bdentrepalos`.`Factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`ConsumoTrabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`ConsumoTrabajador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pago_id` SMALLINT UNSIGNED NULL,
  `Producto_id` INT UNSIGNED NULL,
  `CantidadProducto` TINYINT UNSIGNED NULL,
  `Descripcion` TEXT NULL,
  INDEX `fk_Pago_has_Producto_Pago1_idx` (`Pago_id` ASC),
  INDEX `fk_Pago_has_Producto_Producto1_idx` (`Producto_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Pago_has_Producto_Pago1`
    FOREIGN KEY (`Pago_id`)
    REFERENCES `bdentrepalos`.`Pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `bdentrepalos`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`DetalleOferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`DetalleOferta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Producto_id` INT UNSIGNED NOT NULL,
  `Oferta_id` INT NOT NULL,
  `CantidadProducto` SMALLINT NOT NULL,
  INDEX `fk_Producto_has_Ofertas_Ofertas1_idx` (`Oferta_id` ASC),
  INDEX `fk_Producto_has_Ofertas_Producto1_idx` (`Producto_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_Producto_has_Ofertas_Ofertas1`
    FOREIGN KEY (`Oferta_id`)
    REFERENCES `bdentrepalos`.`Oferta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Ofertas_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `bdentrepalos`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdentrepalos`.`Imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdentrepalos`.`Imagen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Ruta` VARCHAR(150) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Producto_id` INT UNSIGNED NULL,
  `Oferta_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Ruta_UNIQUE` (`Ruta` ASC),
  INDEX `fk_Imagen_Producto1_idx` (`Producto_id` ASC),
  INDEX `fk_Imagen_Oferta1_idx` (`Oferta_id` ASC),
  CONSTRAINT `fk_Imagen_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `bdentrepalos`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imagen_Oferta1`
    FOREIGN KEY (`Oferta_id`)
    REFERENCES `bdentrepalos`.`Oferta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
